allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@langchain/langgraph-sdk@1.9.6'
  - '@assistant-ui/core@0.2.5'
  - '@assistant-ui/react-langchain@0.0.8'
  - '@assistant-ui/react@0.14.8'
  - '@assistant-ui/store@0.2.12'
  - '@assistant-ui/tap@0.5.12'
  - assistant-cloud@0.1.29
  - assistant-stream@0.3.16
  - safe-content-frame@0.0.20
